INSERT INTO RegistrationForm (
    UniversityRollNo, 
    EmailAddress, 
    FirstName, 
    LastName, 
    Branch, 
    Department, 
    Year, 
    PhoneNumber, 
    SelectedEvents, 
    Gender, 
    Semester, 
    Payment_Verified, 
    Transaction_ID, 
    Transaction_Amount
) VALUES (
    '123456789', 
    'student@example.com', 
    'John', 
    'Doe', 
    'Computer Science', 
    'Engineering', 
    3, 
    '1234567890', 
    ARRAY['Event1', 'Event2'], 
    'Male', 
    6, 
    FALSE, 
    NULL, 
    NULL
);
